# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: Conda Tests

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  tests:
    name: "Conda"
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout üõéÔ∏è
        uses: "actions/checkout@v2"

      - name: Setup Python üêç
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env
          conda-build-version: 3.21.0

      - name: Install dependencies üîß
        shell: bash
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade "whey-conda" "whey"

          $CONDA/bin/conda config --add channels conda-forge
          $CONDA/bin/conda config --add channels domdfcoding

      - name: "Build and index channel"
        run: |
          python -m whey --builder whey_conda --out-dir conda-bld/noarch
          $CONDA/bin/conda index ./conda-bld || exit 1

      - name: "Search for package"
        run: |
          $CONDA/bin/conda search -c file://$(pwd)/conda-bld whey-conda
          $CONDA/bin/conda search -c file://$(pwd)/conda-bld --override-channels whey-conda

      - name: "Install package"
        run: |
          $CONDA/bin/conda install -c file://$(pwd)/conda-bld whey-conda=0.1.2=py_1 -y || exit 1

      - name: "Run Tests"
        run: |
          rm -rf whey_conda
          which -a pip
          which -a python
          pip install -r tests/requirements.txt
          python -m pytest tests/
